name: DEMO

on: 
  push: 
  
jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: docker run -d --name nginx-demo-container -p 8080:80 demo
      - run: curl localhost:8080