name: DEMO

on: 
  push: 
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: docker build -t demo .
      - name: Run
        run: docker run -d --name nginx-demo-container -p 8080:80 demo
      

  logs:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@4
      - name: Listing Running Containers
        run: docker ps
      - name: Showing DOCKER LOGS
        run: docker logs nginx-demo-container

  deploy:
    needs: logs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@4
      - name : curl
        run: localhost:8080